### PR TITLE
More plot.naRes and plot.dimRes options

### LINKED ISSUE #266: More options for plot.naRes
1. 
the missing values plot function: 
https://github.com/pmartR/pmartR/blob/cee873908df744c09af4332b2b9e80cd010665f3/R/plot_fns.R#L1046

Has an option for ordering and coloring by a value in f_data.  However we also want to be able to color/order by the group assignment in group_DF (`attr(object, 'group_DF')$Group`).

2.
We also want the option for the bar heights to be:  
- the number of NON-missing values as well as missing values
- the _proportion_ of missing/non-missing values

### PR DESCRIPTION
**Pull request by evanglass**
Closes #266

### CODE REVIEW

**Comment by evanglass** [comment]
One more thing I noticed is that the 'scatter' mode of plot.naRes doesn't respect the color_by parameter. Do you want me to make it do that?

**Comment by clabornd** [comment]
> One more thing I noticed is that the 'scatter' mode of plot.naRes doesn't respect the color_by parameter. Do you want me to make it do that?

Oh really...yea if you could fix that please, good catch.

**Comment by evanglass** [comment]
Actually, looking over how it actually works, I can see why it doesn't do it. Each point is the mean of all the values for a particular biomolecule in a particular group. In other words, the values for variables that aren't part of the group designation just get averaged, so they can't be colored individually.

**Comment by clabornd** [comment]
> Actually, looking over how it actually works, I can see why it doesn't do it. Each point is the mean of all the values for a particular biomolecule in a particular group. In other words, the values for variables that aren't part of the group designation just get averaged, so they can't be colored individually.

Ah I see, makes sense.  I'll give this a spin in the app once my new R environment is all set up then I think we're good to go.

**Pull request merged**
