### PR TITLE
Feature/GitHub actions

### PR DESCRIPTION
**Pull request by clabornd**
Add github actions R-CMD-Check and pkdown.  The way it should work is:

1. Any pull request or code change to master/develop will trigger R-CMD-check
2. Any pull request or code change to master/develop will trigger a build (NOT deployment) of a github pages site.  The site will deploy ONLY on a code change to master.

The various changes I made are essentially to get R-CMD-check to pass, but they are not complete fixes - The vignettes still need to be updated and various function documentation is incomplete.

I also snuck in a fix to get_spans_params() in R/spans.R that appeared when running R-CMD-check

### CODE REVIEW

**Comment by stratkg** [comment]
This all looks good to me

**Review by stratkg — APPROVED** [review]
Merge conflicts just need to be resolved, but otherwise this is great

**Comment by stratkg** [comment]
Also need to increment the version number please :)

**Comment by clabornd** [comment]
Version bumped, conflicts fixed.  I also made some changes:

- Bunch of stuff for the new `imd_anova` parameters (pval_adjust_a_multcomp etc.)
- **Removed a bunch of files in the top level.  Let me know if I removed something that was needed - I also removed docs/, since github actions will now build the contents of that directory and put it in its own separate branch (gh-pages).**
- Added `dontrun` around some examples with spans and seqdata to reduce CI time (was taking over an hour)

**Pull request merged**
