### PR TITLE
Fix #280

### LINKED ISSUE #280: Plotting dimres object fails if fdata_cname is not "SampleID"
```r
library(pmartRdata)
library(pmartR)

myobj <- edata_transform(pmartRdata::lipid_neg_object, 'log2')

# change fdata_cname to 'newcol'
myobj$f_data <- myobj$f_data %>% dplyr::rename("newcol" = "SampleID")
attr(myobj, "cnames")$fdata_cname = "newcol"

# run group designation here
myobj <- group_designation(myobj, "Virus")

mydimres = dim_reduction(myobj)

# or color_by...
plot(mydimres, myobj, shape_by = "newcol")
```

```
> Error in `[[<-.data.frame`(`*tmp*`, shape_by, value = integer(0)) :  
    replacement has 0 rows, data has 45
```

I believe the culprits are these lines:
https://github.com/pmartR/pmartR/blob/8b6c852fee53717ced36590eaa76185bced641ae/R/plot_fns.R#L1978C20-L1978C20

`merge.data.frame` removes the join column on the right side of the join, so it doesn't exist when the function tries to subset by `shape_by`, which the user specified to be the `fdata_cname`.

Edit:  The above example happens just because no such column exists, the issue with merge happens specifically when group_designtation has been applied

### PR DESCRIPTION
**Pull request by evanglass**

### CODE REVIEW

**Comment by clabornd** [comment]
Think we still need to append the f_data in the last else clause:  https://github.com/pmartR/pmartR/blob/466cf8a9e04cd450417406af91d16bc6f4eef74c/R/plot_fns.R#L2025 if the user wanted to color by something in f_data.  

Also wondering if there's any way the sample id's could be in a different order in plot data and group_DF.  In that case the assignment `plotdata[[fdata_cname]] <- group_DF[[fdata_cname]]` might cause misalignment.  If we're able to keep fdata_cname from the right side of the join/merge I think this case would be covered

**Comment by evanglass** [comment]
I don't believe it's possible to do this since the dimres object doesn't store f_data/fdata_cname unless it has a group_DF.

As for the second concern, I think you're right, in theory if the names(e_data) is different order than f_data[[fdata_cname]] it will produce the wrong result.

I think doing `plotdata[[fdata_cname]] <- plotdata[[plotdata_name]]` instead should fix this. I'll add a commit in a minute.

**Comment by clabornd** [comment]
> I don't believe it's possible to do this since the dimres object doesn't store f_data/fdata_cname unless it has a group_DF.

Ah right, I was confusing this with plot.naRes where we have omicsData.

Nice simple solution with the column reassignment.  Does the same thing need to happen after these merges on 1939 and 1946 as well:  https://github.com/pmartR/pmartR/blob/b8c5c1d151008f25296aa4893b077eaa1411a503/R/plot_fns.R#L1939 ?

I'll merge this next week with some other small fixes, thanks.

**Comment by clabornd** [comment]
Looks good to me, will probably get the CRAN branch merged in first then rebase this one

**Pull request merged**
