### PR TITLE
Update filter_objects.R

### LINKED ISSUE #332: proteomics filter can't handle redundancy with non-standard emeta_cname
Error on the example below, working on fix to ensure filter tables don't use checknames

```
library(pmartR)
library(pmartRdata)

e_data <- pmartRdata::pep_edata
edata_cname <- "Peptide"

f_data <- pmartRdata::pep_fdata
fdata_cname <- "SampleID"

e_meta <- pmartRdata::pep_emeta

## Induce redundancy
pep <- e_meta[1, "Peptide"]
df <- e_meta[2,]
df$Peptide <- pep
e_meta <- rbind(e_meta, df)

## Inconvenient name
e_meta[["Razor protein"]] <- e_meta$RazorProtein
emeta_cname <- "Razor protein"

pep_object <- as.pepData(
  e_data = e_data,
  f_data = f_data,
  e_meta = e_meta,
  edata_cname = edata_cname,
  fdata_cname = fdata_cname,
  emeta_cname = emeta_cname
)

my_filter <- proteomics_filter(omicsData = pep_object)
plot(my_filter, "redundancy")

applyFilt(filter_object = my_filter, omicsData = pep_object, min_num_peps = 2, redundancy = T)
```

### PR DESCRIPTION
**Pull request by rarichardson92**
closes #332 

@clabornd would you check this guy out?

### CODE REVIEW

**Comment by rarichardson92** [comment]
We also might need a more comprehensive switch to check.names = FALSE across the package

**Comment by clabornd** [comment]
Yea I get the same error, thanks for finding this.

Evan did a cleanup of the check.names a bit ago in #240, but I guess one slipped back in here:  https://github.com/pmartR/pmartR/commit/4a2a88bf8d7f308d18c3dbd65cab5f5f507e7803

We'll just have to be more diligent about making sure its either `data.frame(check_names=FALSE)` or `as.data.frame()`.

**Comment by rarichardson92** [comment]
@clabornd I didn't do any messing with tibbles since I'm not 100% sure which packages/functions automatically spit out tibbles vs lists vs matrixes, but I ended up doing a broad sweep on as.data.frame and data.frame with some string replacement since as.data.frame also supports the check.names argument. Figured there's never really a time we want R to correct our tables!

Perhaps we ought to update the test files to have wonky column names for future dev? I think that's the easiest solution for now, though a do think a format-like checker might be useful down the line for a list of rules, such as data.frame must include  check.names = FALSE, etc.

**Comment by clabornd** [comment]
Thanks, I think before merging I'll revert in some places where we don't need check.names=FALSE like where certain dataframes are manually constructed with valid names, just to keep things tidy.  

Yea some tests like that would be a good addition.  Been thinking about making a change to do check.names up-front in as.xxData since thats the main bottleneck where this becomes a problem so I'll try to include tests in that change.

**Comment by clabornd** [comment]
Closing and merging the backup #335

**Pull request closed without merging**
