### PR TITLE
App based changes

### PR DESCRIPTION
**Pull request by rarichardson92**
Updates based on app-discovered issues, e.g. same edata and fdata name, mean column reporting, summary fixes

### CODE REVIEW

**Comment by clabornd** [comment]
Tests pass, but am getting a couple errors in the vignette building:

```
Quitting from lines 268-274 (Statistical_Analysis_with_pmartR.Rmd) 
Error: processing vignette 'Statistical_Analysis_with_pmartR.Rmd' failed with diagnostics:
replacement has 0 rows, data has 18106

Quitting from lines 464-468 (Typical_Processing_Workflow.Rmd) 
Error: processing vignette 'Typical_Processing_Workflow.Rmd' failed with diagnostics:
replacement has 0 rows, data has 9830
```

Seems to be the same error somewhere in `make_volcano_plot_df`

**Comment by clabornd** [comment]
Doesn't throw an error on anything, but just checking if this gsub is still valid since you removed some of the other ones:  https://github.com/pmartR/pmartR/blob/50f1e02f5d1ded5b99f3aea2e0034fae57bf8d89/R/seqData_wrappers.R#L368

**Review by stratkg — APPROVED** [review]
Package builds, documentation is up to date. I was able to use all of the changed functionality, getting no errors or unexpected results. I admit that I don't follow all of the changes--not sure how fdata_cname could ever be the same as edata_cname, for instance. But things are not breaking.

**Comment by rarichardson92** [comment]
Recent commit addresses Dan's points, ready to merge :)

**Review by clabornd — APPROVED** [review]

**Pull request merged**
