### PR TITLE
Develop test

### PR DESCRIPTION
**Pull request by rarichardson92**

### CODE REVIEW

**Comment by clabornd** [comment]
This passes all tests and builds from remotes:: on my machine.  @stratkg if that is good enough for you then merge away.  I may take a stab at cleaning up the commit history - removing duplicate commits like "default check for valid f_meta among f_datas".

**Comment by clabornd** [comment]
@stratkg sry, maybe don't quite yet.  734af978925b6cd6f8dbee07014d2d3aeeeea250 undoes some changes from 6556d6ff0fb0bf3b2a97f6b06198bb38293ce79f on develop.

**Comment by clabornd** [comment]
@stratkg @rarichardson92 Ok, I made a new branch "develop_test_clean", which drops the following commits, all of which I believe are unnecessary, and some of which I believe might cause problems:

- [dcd5575](https://github.com/pmartR/pmartR/pull/210/commits/dcd5575f1b3576fdd2f90350cb88fc9776e268bd)
- [57be6c4](https://github.com/pmartR/pmartR/pull/210/commits/57be6c4a9be016f4219915409d16bb5d65bdc5a1)
- [29e0a34](https://github.com/pmartR/pmartR/pull/210/commits/29e0a3405cf0ac5368550b0f80ee4b0c2e74bd89)
- [ab76fa7](https://github.com/pmartR/pmartR/pull/210/commits/ab76fa73834c9a22ee5184f73c6381d5826fb6dd)
- [14d5dba](https://github.com/pmartR/pmartR/pull/210/commits/14d5dba7901b8c8706ef2ef0fc906e33123f16d0)
- [b754938](https://github.com/pmartR/pmartR/pull/210/commits/b75493827562062a3d63441a0060ccf3604385c0)
- [b235c5f](https://github.com/pmartR/pmartR/pull/210/commits/b235c5f0413e2f28b4f5f6b4b40918bab2d821f7)
- [4fa4e4e](https://github.com/pmartR/pmartR/pull/210/commits/4fa4e4e30b1a0bd3378d5b53153ea84238810c9a)
- [de5a5dd](https://github.com/pmartR/pmartR/pull/210/commits/de5a5ddca2231b86aaa1f1c4e1185309de079364)
- [734af97](https://github.com/pmartR/pmartR/pull/210/commits/734af978925b6cd6f8dbee07014d2d3aeeeea250)
- [d6c2847](https://github.com/pmartR/pmartR/pull/210/commits/d6c28471be4a312fddd51b32780ce6744a4c54fe)
- [4721586](https://github.com/pmartR/pmartR/pull/210/commits/4721586f44ebce86fa33ee69f1525101db82b9e8)
- [d753a0f](https://github.com/pmartR/pmartR/pull/210/commits/d753a0f8e8d3ffdd926366aa8f9b7d36a67e17ed)
- [90387ed](https://github.com/pmartR/pmartR/pull/210/commits/90387ed33d62a3023679daa9124d411790d4d24d)

That branch still passes all tests on my machine and builds from remotes.  I removed some print statements and removed a copy of the RNAseq .Rmd from the top directory, lemme know if either of these is incorrect.  If it looks good to you all I recommend porting this PR to that branch.

**Comment by rarichardson92** [comment]
Refer to PR #211

**Pull request closed without merging**
